@echo off
echo Starting Academic Chatbot...
echo.
echo Step 1: Downloading NLTK data (first time only)...
python setup_nltk.py
echo.
echo Step 2: Starting Streamlit application...
streamlit run app/main.py
